name: Patch Missed Streak

on:
  workflow_dispatch:

jobs:
  backdate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Backdated Commit
        run: |
          git config --global user.name "rydhym"
          git config --global user.email "agarwalrydhym@gmail.com"

          MISSED_DATE="2026-06-25T12:00:00+05:30"

          GIT_AUTHOR_DATE="$MISSED_DATE" \
          GIT_COMMITTER_DATE="$MISSED_DATE" \
          git commit --allow-empty -m "Fixing July 18 streak"

          git push origin main
